version: "3.1"
volumes:
    blog-database-data:
        driver: local
services:
    db:
        image: mysql
        container_name: find-me-database
        volumes:
            - blog-database-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
    php:
        build: ./docker
        container_name: find-me-php
        extra_hosts:
            - host.docker.internal:host-gateway
        working_dir: /var/www
        volumes:
            - ./:/var/www/
            - ./docker/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini
        environment:
            - PHP_IDE_CONFIG=serverName=${APP_NAME}
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: find-me-server
        working_dir: /var/www
        depends_on:
            - php
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/
        ports:
            - "7896:80"

