openapi: 3.0.3
info:
  title: Blog
  description: Blog
  version: 1.0.0
servers:
  - url: http://localhost:80/api

paths:
  /auth/register:
    post:
      $ref: './Schemas/User/paths/auth-register.yaml'
  /auth/login:
    post:
      $ref: './Schemas/User/paths/auth-login.yaml'
  /auth/logout:
    post:
      $ref: './Schemas/User/paths/auth-logout.yaml'
  /auth/me:
    get:
      $ref: './Schemas/User/paths/auth-me.yaml'
  /auth/verify:
    post:
      $ref: './Schemas/User/paths/auth-verify.yaml'