name: FindMe Front CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - uses: actions/checkout@v2


      - name: Install dependencies
        run: npm i

      - name: Typecheck
        run: npm run typecheck

      - name: Run test suite
        run: npm test

